---
name: Publish

on:
  create:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '8'
          java-package: jdk
          architecture: x64
      - name: Set Release Version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Create JAR
        run: |
          echo ${{ github.sha }} > Release.txt
          mkdir -p "out/github/tools/client" "out/github/tools/responseObjects"
          cp -a src/github/tools/client/. out/github/tools/client/
          cp -a src/github/tools/responseObjects/. out/github/tools/responseObjects/
          cd out
          javac github/tools/client/*.java github/tools/responseObjects/*.java
          jar cf GitHubApiClient.jar github/tools/client/*.class github/tools/responseObjects/*.class
          cd ..
          cp out/GitHubApiClient.jar ./GitHubApiClient-${{ env.RELEASE_VERSION }}.jar
      - name: Test
        run: cat Release.txt
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            GitHubApiClient-${{ env.RELEASE_VERSION }}.jar
            Release.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
